/**
 * Domain types.
 *
 * These are hand-written for Phase 1 so the UI shell can be typed before the
 * database exists. In Phase 2, once the migrations are applied, we generate
 * `database.types.ts` from the live schema with the Supabase CLI and re-express
 * these as aliases over the generated Row types. Keeping them in one file makes
 * that swap a single-file change.
 */

export type UserRole = "user" | "admin";

export type MeetingPlatform = "google_meet" | "zoom" | "other";

export type AudioProvider = "supabase_storage" | "google_drive" | "external";

export type QuizOption = "a" | "b" | "c" | "d";

export interface Profile {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

export interface Chapter {
  id: string;
  chapter_number: number;
  name_sanskrit: string;
  name_marathi: string;
  description: string | null;
  total_verses: number;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface Verse {
  id: string;
  chapter_id: string;
  verse_number: number;
  sanskrit_text: string;
  word_to_word: string | null;
  translation: string | null;
  purport: string | null;
  /** Written by the administrator. Never generated by the application. */
  easy_explanation: string | null;
  /** Written by the administrator. Never generated by the application. */
  example: string | null;
  audio_url: string | null;
  audio_provider: AudioProvider | null;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface VerseProgress {
  id: string;
  user_id: string;
  verse_id: string;
  is_read: boolean;
  is_memorized: boolean;
  read_at: string | null;
  memorized_at: string | null;
  total_time_seconds: number;
  created_at: string;
  updated_at: string;
}

export interface ReadingSession {
  id: string;
  user_id: string;
  verse_id: string;
  started_at: string;
  ended_at: string;
  duration_seconds: number;
  created_at: string;
}

export interface ClassSession {
  id: string;
  title: string;
  description: string | null;
  /** ISO date, e.g. "2026-10-05". */
  class_date: string;
  /** 24-hour local time, e.g. "19:30". */
  class_time: string;
  meeting_platform: MeetingPlatform;
  meeting_url: string;
  is_published: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface Quiz {
  id: string;
  title: string;
  description: string | null;
  chapter_id: string | null;
  verse_start: number | null;
  verse_end: number | null;
  is_published: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * A quiz question as stored, including the answer key.
 *
 * Never send this shape to the browser before submission. Use
 * `PublicQuizQuestion` for the attempt UI.
 */
export interface QuizQuestion {
  id: string;
  quiz_id: string;
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_option: QuizOption;
  explanation: string | null;
  display_order: number;
  created_at: string;
  updated_at: string;
}

/** A question with the answer key stripped, for an in-progress attempt. */
export type PublicQuizQuestion = Omit<
  QuizQuestion,
  "correct_option" | "explanation"
>;

export interface QuizAttempt {
  id: string;
  quiz_id: string;
  user_id: string;
  score: number;
  total_questions: number;
  started_at: string;
  completed_at: string | null;
}

export interface QuizAnswer {
  id: string;
  attempt_id: string;
  question_id: string;
  selected_option: QuizOption | null;
  is_correct: boolean;
}

/* --- Derived view models -------------------------------------------------- */

/** A chapter plus the signed-in user's progress through it. */
export interface ChapterWithProgress extends Chapter {
  verses_read: number;
  verses_memorized: number;
}

/** A verse list row: enough to render the list without loading full content. */
export interface VerseListItem {
  id: string;
  verse_number: number;
  preview: string;
  is_read: boolean;
  is_memorized: boolean;
}

/** Aggregate totals for the user dashboard. */
export interface ProgressSummary {
  verses_read: number;
  verses_memorized: number;
  total_time_seconds: number;
  total_verses: number;
}
