-- 0003_content.sql
-- Chapters and verses. Scripture content, managed by the administrator and read
-- by everyone.

create table public.chapters (
  id             uuid primary key default gen_random_uuid(),
  chapter_number integer not null unique check (chapter_number between 1 and 18),
  name_sanskrit  text not null,
  name_marathi   text not null,
  description    text,
  total_verses   integer not null check (total_verses > 0),
  display_order  integer not null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

comment on column public.chapters.total_verses is
  'How many verses the chapter should have (drives progress display). Editable, not derived: editions disagree on counts and content may be imported in stages.';

create trigger chapters_set_updated_at
  before update on public.chapters
  for each row execute function public.set_updated_at();

alter table public.chapters enable row level security;

-- ---------------------------------------------------------------------------
-- verses
--
-- verse_number is the first (or only) verse of the entry. verse_number_end is
-- set only for combined entries -- Bhagavad-gita As It Is groups some verses,
-- e.g. 1.16-18, which the recitation audio also treats as one track. For a
-- single verse, verse_number_end is null and the UI shows "श्लोक 5"; for a
-- range it shows "श्लोक 16-18". Ordering always uses verse_number.
-- ---------------------------------------------------------------------------
create table public.verses (
  id               uuid primary key default gen_random_uuid(),
  chapter_id       uuid not null references public.chapters (id) on delete cascade,
  verse_number     integer not null check (verse_number > 0),
  verse_number_end integer check (verse_number_end is null or verse_number_end >= verse_number),
  sanskrit_text    text not null,
  word_to_word     text,
  translation      text,
  purport          text,
  -- Administrator-authored. Never generated by the application.
  easy_explanation text,
  example          text,
  audio_url        text,
  audio_provider   text check (audio_provider in ('supabase_storage', 'google_drive', 'external')),
  display_order    integer not null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  -- One entry per starting verse number within a chapter. Prevents an import
  -- from creating duplicate rows for the same verse.
  unique (chapter_id, verse_number)
);

comment on column public.verses.verse_number_end is
  'Non-null only for combined entries like 1.16-18. Null means a single verse.';
comment on column public.verses.easy_explanation is
  'Administrator-authored. The application never generates this.';
comment on column public.verses.example is
  'Administrator-authored. The application never generates this.';

create index verses_chapter_id_display_order_idx
  on public.verses (chapter_id, display_order);

create trigger verses_set_updated_at
  before update on public.verses
  for each row execute function public.set_updated_at();

alter table public.verses enable row level security;
